"""Resource-oriented public QRadar API."""

from __future__ import annotations

from typing import Any, Optional

from .._http import QRadarSession
from ._base import ResourceBase


class SavedSearchesResultsResource(ResourceBase):
    """Operations below ``/asset_model/saved_searches/{saved_search_id}/results``."""

    def list(self, saved_search_id, filter: Optional[Any]=None, fields: Optional[Any]=None, range_header: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieves a list of assets based on the results of an asset saved search.'
        url = f'/asset_model/saved_searches/{saved_search_id}/results'
        return self._s.get(url, range_header=range_header, fields=fields, filter_expr=filter, **kwargs)


class AssetsResource(ResourceBase):
    """Operations below ``/asset_model/assets``."""

    def create(self, **kwargs: Any) -> Any:
        'Creates a new asset. An asset contains the following fields:'
        url = '/asset_model/assets'
        return self._s.post(url, **kwargs)

    def delete(self, asset_id, **kwargs: Any) -> Any:
        'Deletes a Asset by ID.'
        url = f'/asset_model/assets/{asset_id}'
        return self._s.delete(url, **kwargs)

    def list(self, filter: Optional[Any]=None, fields: Optional[Any]=None, range_header: Optional[Any]=None, sort: Optional[Any]=None, **kwargs: Any) -> Any:
        'This lists all assets found in the model.  This endpoint supports sorting on id, domain_id, vulnerability_count and risk_score_sum, and filtering on all fields.  EXCEPTION:  LIKE, ILIKE, and BETWEEN do not work on the interfaces(ip_addresses(value)) field.  It is possible to use the inequality operators to work around this in most cases.  Use of the fields header to request only the necessary fields will improve API performance.'
        url = '/asset_model/assets'
        return self._s.get(url, range_header=range_header, fields=fields, filter_expr=filter, sort=sort, **kwargs)

    def update(self, asset_id, body: Optional[Any]=None, **kwargs: Any) -> Any:
        'Update an asset with several pertinent pieces of information.'
        url = f'/asset_model/assets/{asset_id}'
        return self._s.post(url, json_body=body, **kwargs)


class ConfigurationResource(ResourceBase):
    """Operations below ``/asset_model/configuration``."""

    def create(self, body: Optional[Any]=None, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Update asset configuration fields.'
        url = '/asset_model/configuration'
        headers = {'fields': fields}
        headers = {k: v for k, v in headers.items() if v is not None}
        return self._s.post(url, headers=headers, json_body=body, **kwargs)

    def get(self, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieve the current configuration settings pertaining to assets.\n//@param frameworkServices An instance of the FrameworkServices class automatically provided by the REST API framework or generated by FrameworkServicesUtil.'
        url = '/asset_model/configuration'
        return self._s.get(url, fields=fields, **kwargs)


class PropertiesResource(ResourceBase):
    """Operations below ``/asset_model/properties``."""

    def list(self, filter: Optional[Any]=None, fields: Optional[Any]=None, range_header: Optional[Any]=None, **kwargs: Any) -> Any:
        'Get a list of available asset property types that can be used.'
        url = '/asset_model/properties'
        return self._s.get(url, range_header=range_header, fields=fields, filter_expr=filter, **kwargs)


class SavedSearchGroupsResource(ResourceBase):
    """Operations below ``/asset_model/saved_search_groups``."""

    def delete(self, group_id, **kwargs: Any) -> Any:
        'Deletes an asset saved search group.'
        url = f'/asset_model/saved_search_groups/{group_id}'
        return self._s.delete(url, **kwargs)

    def get(self, group_id, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieves an asset saved search group.'
        url = f'/asset_model/saved_search_groups/{group_id}'
        return self._s.get(url, fields=fields, **kwargs)

    def list(self, filter: Optional[Any]=None, fields: Optional[Any]=None, range_header: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieves a list the asset saved search groups.'
        url = '/asset_model/saved_search_groups'
        return self._s.get(url, range_header=range_header, fields=fields, filter_expr=filter, **kwargs)

    def update(self, group_id, body: Optional[Any]=None, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Updates the owner of an asset saved search group.'
        url = f'/asset_model/saved_search_groups/{group_id}'
        headers = {'fields': fields}
        headers = {k: v for k, v in headers.items() if v is not None}
        return self._s.post(url, headers=headers, json_body=body, **kwargs)


class SavedSearchesResource(ResourceBase):
    """Operations below ``/asset_model/saved_searches``."""

    def __init__(self, session: QRadarSession) -> None:
        super().__init__(session)
        self.results: SavedSearchesResultsResource = SavedSearchesResultsResource(session)

    def delete(self, saved_search_id, **kwargs: Any) -> Any:
        'Deletes an asset saved search.'
        url = f'/asset_model/saved_searches/{saved_search_id}'
        return self._s.delete(url, **kwargs)

    def get(self, saved_search_id, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieves an asset saved search.'
        url = f'/asset_model/saved_searches/{saved_search_id}'
        return self._s.get(url, fields=fields, **kwargs)

    def list(self, filter: Optional[Any]=None, fields: Optional[Any]=None, range_header: Optional[Any]=None, **kwargs: Any) -> Any:
        'Retrieves a list of saved searches that can be used or applied against the /asset_model/saved_searches/{saved_search_id}/results query.'
        url = '/asset_model/saved_searches'
        return self._s.get(url, range_header=range_header, fields=fields, filter_expr=filter, **kwargs)

    def update(self, saved_search_id, body: Optional[Any]=None, fields: Optional[Any]=None, **kwargs: Any) -> Any:
        'Updates the asset saved search owner only.'
        url = f'/asset_model/saved_searches/{saved_search_id}'
        headers = {'fields': fields}
        headers = {k: v for k, v in headers.items() if v is not None}
        return self._s.post(url, headers=headers, json_body=body, **kwargs)


class AssetModelAPI(ResourceBase):
    """Resource-oriented client for the ``asset_model`` endpoints."""

    def __init__(self, session: QRadarSession) -> None:
        super().__init__(session)
        self.assets: AssetsResource = AssetsResource(session)
        self.configuration: ConfigurationResource = ConfigurationResource(session)
        self.properties: PropertiesResource = PropertiesResource(session)
        self.saved_search_groups: SavedSearchGroupsResource = SavedSearchGroupsResource(session)
        self.saved_searches: SavedSearchesResource = SavedSearchesResource(session)
